import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import "./globals.css";
import { Providers } from "./providers";
import Header from '../components/general/header';
import ClientOnly from '../components/auth/ClientOnly';
import SessionExpiredHandler from '../components/auth/SessionExpiredHandler';
import TokenExpirationChecker from '../components/auth/TokenExpirationChecker';
import BackendStatus from '../components/general/BackendStatus';

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <Providers>
          <ClientOnly>
            <SessionExpiredHandler />
            <TokenExpirationChecker />
            <BackendStatus />
          </ClientOnly>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
