import type { Metadata } from "next";
import { Roboto, Poppins } from 'next/font/google';
import "./globals.css";
import { Providers } from "./providers";
import HeaderWrapper from '@/components/general/HeaderWrapper';
import ClientOnly from '../components/auth/ClientOnly';
import SessionExpiredHandler from '../components/auth/SessionExpiredHandler';
import TokenExpirationChecker from '../components/auth/TokenExpirationChecker';
// import BackendStatus from '../components/general/BackendStatus';

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${poppins.variable}`}>
        <Providers>
          <ClientOnly>
            <SessionExpiredHandler />
            <TokenExpirationChecker />
            {/* <BackendStatus /> */}
          </ClientOnly>
          <HeaderWrapper />
          {children}
        </Providers>
      </body>
    </html>
  );
}
