-- Update enum values to match Java enums
ALTER TABLE product_inventory_log MODIFY COLUMN transaction_type ENUM('IN', 'OUT', 'SET') NOT NULL;
ALTER TABLE product_inventory_log MODIFY COLUMN transaction_source_type ENUM(
    'PURCHASE_ORDER_RECEIPT',
    'PRODUCTION_COMPLETION', 
    'CUSTOMER_RETURN',
    'PRODUCT_ADJUSTMENT_INCREASE',
    'PRODUCT_WAREHOUSE_TRANSFER_IN',
    'SALES_ORDER_FULFILLMENT',
    'PRODUCTION_CONSUMPTION',
    'SUPPLIER_RETURN',
    'INVENTORY_ADJUSTMENT_DECREASE',
    'WAREHOUSE_TRANSFER_OUT',
    'SCRAP',
    'SET_INVENTORY'
) NOT NULL;
ALTER TABLE product_inventory_log MODIFY COLUMN reference_document_type ENUM(
    'SALES_ORDER',
    'PRODUCTION_TICKET', 
    'INVENTORY_ADJUSTMENT',
    'PURCHASE_ORDER',
    'PRODUCTION_ORDER',
    'WAREHOUSE_TRANSFER'
); 